2021-06-06 21:07:11,382 - __main__ - INFO - application started
2021-06-06 21:07:11,383 - __main__ - INFO - Train size: 6000
2021-06-06 21:07:11,384 - __main__ - INFO - Test size: 1000
2021-06-06 21:07:11,385 - __main__ - INFO - Tune parameter: False
2021-06-06 21:07:11,386 - tools - INFO - getting data from mnist_784
2021-06-06 21:07:35,010 - tools - INFO - split data to train and test set
2021-06-06 21:07:35,213 - __main__ - INFO - no parameters tuned
2021-06-06 21:07:35,214 - __main__ - INFO - create and fit model
2021-06-06 21:07:35,215 - __main__ - INFO - initialize model
2021-06-06 21:07:35,216 - __main__ - INFO - fitting model on train data
2021-06-06 21:07:35,354 - __main__ - INFO - Score of model on train set: 0.9988333333333334
2021-06-06 21:07:35,377 - __main__ - INFO - Score of model on test set: 0.882
2021-06-06 21:07:36,818 - tools - INFO - Classification Report: 
2021-06-06 21:07:36,819 - tools - INFO - {'0': {'precision': 0.9183673469387755, 'recall': 0.9473684210526315, 'f1-score': 0.9326424870466321, 'support': 95}, '1': {'precision': 0.9426229508196722, 'recall': 0.9583333333333334, 'f1-score': 0.950413223140496, 'support': 120}, '2': {'precision': 0.8571428571428571, 'recall': 0.9230769230769231, 'f1-score': 0.888888888888889, 'support': 91}, '3': {'precision': 0.75, 'recall': 0.8484848484848485, 'f1-score': 0.7962085308056871, 'support': 99}, '4': {'precision': 0.8709677419354839, 'recall': 0.8709677419354839, 'f1-score': 0.8709677419354839, 'support': 93}, '5': {'precision': 0.8311688311688312, 'recall': 0.7441860465116279, 'f1-score': 0.7852760736196319, 'support': 86}, '6': {'precision': 0.9607843137254902, 'recall': 0.9245283018867925, 'f1-score': 0.9423076923076923, 'support': 106}, '7': {'precision': 0.9428571428571428, 'recall': 0.9166666666666666, 'f1-score': 0.9295774647887323, 'support': 108}, '8': {'precision': 0.8735632183908046, 'recall': 0.8172043010752689, 'f1-score': 0.8444444444444446, 'support': 93}, '9': {'precision': 0.8584905660377359, 'recall': 0.8348623853211009, 'f1-score': 0.8465116279069768, 'support': 109}, 'accuracy': 0.882, 'macro avg': {'precision': 0.8805964969016793, 'recall': 0.8785678969344678, 'f1-score': 0.8787238174884667, 'support': 1000}, 'weighted avg': {'precision': 0.8835787312299953, 'recall': 0.882, 'f1-score': 0.8819799811732221, 'support': 1000}}
2021-06-06 21:07:36,823 - tools - INFO - Confusion Report: 
2021-06-06 21:07:36,824 - tools - INFO - [[90, 0, 1, 2, 0, 1, 0, 0, 1, 0], [0, 115, 1, 2, 1, 1, 0, 0, 0, 0], [2, 1, 84, 2, 0, 0, 0, 1, 1, 0], [0, 1, 6, 84, 1, 4, 0, 1, 1, 1], [0, 0, 0, 1, 81, 0, 1, 0, 1, 9], [3, 1, 1, 12, 0, 64, 1, 0, 2, 2], [2, 0, 1, 0, 1, 1, 98, 0, 3, 0], [0, 2, 2, 2, 3, 0, 0, 99, 0, 0], [1, 2, 1, 4, 0, 4, 2, 0, 76, 3], [0, 0, 1, 3, 6, 2, 0, 4, 2, 91]]
2021-06-06 21:07:36,880 - werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-06-06 21:07:36,881 - werkzeug - INFO -  * Running on http://172.18.0.2:5000/ (Press CTRL+C to quit)
2021-06-06 21:07:42,371 - werkzeug - INFO - 172.18.0.1 - - [06/Jun/2021 21:07:42] "GET / HTTP/1.1" 200 -
2021-06-06 21:07:42,416 - werkzeug - INFO - 172.18.0.1 - - [06/Jun/2021 21:07:42] "GET /static/confusion_matrix.jpeg HTTP/1.1" 200 -
2021-06-06 21:07:47,248 - main - ERROR - Exception on /5 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/main.py", line 137, in get_prediction
    return render_template(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/index_html_template.html", line 11, in top-level template code
    <img src="{{ url_for('data', filename='tmp.jpeg') }}" width="200" height="200" alt="start" />
  File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/usr/local/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'data' with values ['filename']. Did you mean 'static' instead?
2021-06-06 21:07:47,256 - werkzeug - INFO - 172.18.0.1 - - [06/Jun/2021 21:07:47] "[35m[1mGET /5 HTTP/1.1[0m" 500 -
2021-06-06 21:08:36,788 - werkzeug - INFO - 172.18.0.1 - - [06/Jun/2021 21:08:36] "GET / HTTP/1.1" 200 -
2021-06-06 21:08:36,826 - werkzeug - INFO - 172.18.0.1 - - [06/Jun/2021 21:08:36] "GET /static/confusion_matrix.jpeg HTTP/1.1" 200 -
